(defun insert (X N LST)
   (cond ((NULL LST) (cons X LST))
      ((eq N 1) (cons X LST))
      (T (cons (car LST)
            (insert X (- N 1)
               (CDR LST)
            )
         )
      )
   )
)
(defun input ()
    (print "Список:")(print LIST)
    (print "Введите вставляемый элемент") 
    (set 'N (read))
    (print "Введите место вставки") 
    (set 'P (read))
    (print "Список после добавления элемента:")
    (set 'LIST(insert N P LIST ))

)
(set 'LIST '(76 7 13 5 32 3 667 1))
(input)